### ISSUE TITLE
I want to resize images.. how can I do this?

### ISSUE THREAD

**Issue by 2jiwon** [KitchenStories/vue-gallery-slideshow#9]
Hello, I've found this and applied and it works great. Thank you.
Now I want to resize popup images size.  How can I resize image size of this?
I barely know about VueJs. Could you teach me how to do it?
I'm sorry if it's not appropriate to ask here. I don't know where to ask.

**Comment by headione** [comment]
Hi, good to hear that you are using my component! I did’t made it customizable but you can fork this repository and modify the styles in the vue file under src/components/VueGallerySlideshow.vue
You can create a bundle via webpack and command ‘npm build’ (please see under scripts in package.json) 
A more easy solution would be overwriting existing classes with !important statement but this a bit hacky.
I hope I could help a bit, otherwise just let me know :)

**Comment by 2jiwon** [comment]
Thank you for the kind comment. I'll try what you said.
